/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package server;

import com.corundumstudio.socketio.AckRequest;
import com.corundumstudio.socketio.Configuration;
import com.corundumstudio.socketio.SocketIOClient;
import com.corundumstudio.socketio.SocketIOServer;
import com.corundumstudio.socketio.listener.ConnectListener;
import com.corundumstudio.socketio.listener.DataListener;
import com.corundumstudio.socketio.listener.DisconnectListener;
import data.DataClient;
import data.DataFileSending;
import data.DataInitFile;
import data.DataWriter;
import java.io.File;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        disconnectedMenu = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cmdStart = new javax.swing.JButton();

        disconnectedMenu.setText("Disconnect this Client");
        disconnectedMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectedMenuActionPerformed(evt);
            }
        });
        menu.add(disconnectedMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "No", "Name"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(0);
            table.getColumnModel().getColumn(0).setPreferredWidth(0);
            table.getColumnModel().getColumn(0).setMaxWidth(0);
            table.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        cmdStart.setText("Start");
        cmdStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdStart)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdStart)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private final int DEFAULT_PORT = 9999;
    private void cmdStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartActionPerformed
        Configuration configuration = new Configuration();
        configuration.setPort(DEFAULT_PORT);
        SocketIOServer server = new SocketIOServer(configuration);
        
        server.addConnectListener(new ConnectListener(){
            @Override
            public void onConnect(SocketIOClient sioc) {
                DataClient client = new DataClient(sioc, "");
                addTableRow(client);
            }
            
        });
        server.addDisconnectListener(new DisconnectListener(){
            @Override
            public void onDisconnect(SocketIOClient sioc) {
                removeClient(sioc);
            }
            
        });
        server.addEventListener("set_user", String.class, new DataListener<String>(){
            @Override
            public void onData(SocketIOClient sioc, String t, AckRequest ar) throws Exception {
                setUserName(sioc, t);
            }
            
        });
        server.addEventListener("send_file", DataInitFile.class, new DataListener<DataInitFile>(){
            @Override
            public void onData(SocketIOClient sioc, DataInitFile t, AckRequest ar) throws Exception {
                int fileID = initFileTransfer(sioc, t);
                if(fileID > 0){
                    ar.sendAckData(true, fileID);
                }
            }
            
        });
        server.addEventListener("sending", DataFileSending.class, new DataListener<DataFileSending>() {
            @Override
            public void onData(SocketIOClient sioc, DataFileSending t, AckRequest ar) throws Exception {
                if(!t.isFinish()){
                    writeFile(sioc, t);
                    ar.sendAckData(true);
                }else{
                    ar.sendAckData(false);
                    closeFile(sioc, t);
                }
            }
        });
        server.start();
    }//GEN-LAST:event_cmdStartActionPerformed

    private void disconnectedMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectedMenuActionPerformed
        if(table.getSelectedRow()>=0){
            int row = table.getSelectedRow();
            DataClient data = (DataClient) table.getValueAt(row, 0);
            data.getSocketIOClient().sendEvent("exit_app", "");
        }
    }//GEN-LAST:event_disconnectedMenuActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        if(table.getSelectedRow()>=0 && SwingUtilities.isRightMouseButton(evt)){
            menu.show(table, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableMouseReleased
    private void addTableRow(DataClient data){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(data.toRowTable(table.getRowCount()+1));
    }
    private void removeClient(SocketIOClient client){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for(int i = 0; i < table.getRowCount(); i++){
            DataClient data = (DataClient) table.getValueAt(i, 0);
            if(data.getSocketIOClient() == client){
                model.removeRow(i);
                break;
            }
        }
    }
    private void setUserName(SocketIOClient client, String name){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for(int i=0 ; i< table.getRowCount(); i++){
            DataClient data = (DataClient) table.getValueAt(i, 0);
            if(data.getSocketIOClient() == client){
                data.setName(name);
                model.setValueAt(name, i, 2);
                break;
            }
        }
    }
    private int initFileTransfer(SocketIOClient client, DataInitFile dataInitFile){
        int id = 0;
        for(int i=0 ; i< table.getRowCount(); i++){
            DataClient data = (DataClient) table.getValueAt(i, 0);
            if(data.getSocketIOClient() == client){
                try {
                    id = generateFileID();
                    File file = new File("D:/socket_data/"+id+"-"+dataInitFile.getFileName());
                    DataWriter writer = new DataWriter(file, dataInitFile.getFileSize());
                    data.addWriter(writer, id);
                    System.out.println("File init");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            }
        }
        return id;
    }
    private boolean writeFile(SocketIOClient client, DataFileSending file){
        boolean error = false;
        for(int i=0 ; i< table.getRowCount(); i++){
            DataClient data = (DataClient) table.getValueAt(i, 0);
            if(data.getSocketIOClient() == client){
                try {
                    data.writeFile(file.getData(), file.getFileID());
                } catch (Exception e) {
                    error = true;
                    e.printStackTrace();
                }
                break;
            }
        }
        return !error;
    }
    private void closeFile(SocketIOClient client, DataFileSending file){
        for(int i=0 ; i< table.getRowCount(); i++){
            DataClient data = (DataClient) table.getValueAt(i, 0);
            if(data.getSocketIOClient() == client){
                try {
                    data.closeWriter(fileID);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            }
        }
    }
    private int fileID;
    private synchronized int generateFileID(){
        fileID ++;
        return fileID;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdStart;
    private javax.swing.JMenuItem disconnectedMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
